config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  devise_for :users, controllers: { sessions: "users/sessions" }

  root 'welcome#index'

  namespace :admins do
    resources :rides do
      member do
        get :ride_accepted
        get :picked_up
        get :dropped_off
      end
    end
  end

  namespace :users do
    resources :rides
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :timeoutable, :lockable, :validatable

  has_many :rides

  validates_presence_of :name, :phone_number,
                        :car_make, :car_model,
                        :car_passenger_capacity
  validates_length_of :phone_number, minimum: 10, maximum: 10
  validates_numericality_of :car_passenger_capacity

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :admin


  validates_presence_of :pick_up_location,
                        :drop_off_location, 
                        :num_of_passengers

  enum status: { active: 0, accepted: 1, in_transit: 2, complete: 3 }

  scope :not_complete, -> { where(status: [0,1,2]) }
  scope :completed, -> { where(status: 3) }

  include AASM
  aasm column: :status, enum: true do
    state :active, :initial => true
    state :accepted
    state :in_transit
    state :complete

    event :ride_accepted do
      transitions from: :active, to: :accepted
    end

    event :picked_up do
      transitions from: :accepted, to: :in_transit
    end

    event :dropped_off do
      transitions from: :in_transit, to: :complete
    end

  end

  def cost
    ((Time.parse(dropoff_time) - Time.parse(pickup_time))/60) * 3
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rides

  validates_presence_of :name, :phone_number
  validates_length_of :phone_number, minimum: 10, maximum: 10


end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController


  def after_sign_up_path_for(resource)
    admins_rides_path
  end

end

app/controllers/admins/rides_controller.rb
class Admins::RidesController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_current_ride, only: [:index]

  layout 'admins'

  def index
    @rides = Ride.all
    @completed_rides = current_admin.rides.completed

    if request.xhr?
      render layout: false
    else
      render
    end
  end

  def ride_accepted
    find_ride
    @ride.admin = current_admin
    @ride.accepted_time = @ride.updated_at.strftime('%l:%M %P')
    @ride.ride_accepted!
    redirect_to admins_rides_path, notice: "You've accepted a ride."
  end

  def picked_up
    find_ride
    @ride.pickup_time = @ride.updated_at.strftime('%l:%M %P')
    @ride.picked_up!
    redirect_to admins_rides_path
  end

  def dropped_off
    find_ride
    @ride.dropoff_time = @ride.updated_at.strftime('%l:%M %P')
    @ride.dropped_off!
    @current_ride = ''
    redirect_to admins_rides_path
  end

  private

  def set_current_ride
    @current_ride = current_admin.rides.last
  end

  def ride_params
    params.require(:ride).permit(:admin_id, :status)
  end

  def find_ride
    @ride = Ride.find(params[:id])
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admins_rides_path
  end

  def after_sign_up_path_for(resource)
    admins_rides_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :phone_number
    devise_parameter_sanitizer.for(:sign_up) << :car_make
    devise_parameter_sanitizer.for(:sign_up) << :car_model
    devise_parameter_sanitizer.for(:sign_up) << :car_passenger_capacity
  end


  def logged_in?
    if current_user
      true
    else
      false
    end
  end

  def require_login
    unless logged_in?
      redirect_to root_path, notice: 'You must be logged in to perform this action.'
      return false
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    users_rides_path
  end


end

app/controllers/users/rides_controller.rb
class Users::RidesController < ApplicationController
  before_filter :require_login
  before_action :set_current_ride, only: [:index]

  def new
    @ride = current_user.rides.new
  end

  def index
    @rides_count = current_user.rides.count
    @completed_rides = current_user.rides.completed

    if request.xhr?
      render layout: false
    else
      render
    end
  end

  def create
    @ride = current_user.rides.new(ride_params)

    if current_user.rides.not_complete.count == 0
      if @ride.save
        redirect_to users_rides_path, notice: "Ride has been requested."
      else
        flash[:alert] = @ride.errors.full_messages.join(', ')
        render :new
      end
    else
      redirect_to users_rides_path, notice: "You can only have one active ride at a time."
    end
  end

  private

  def ride_params
    params.require(:ride).permit(:pick_up_location, :drop_off_location, :num_of_passengers)
  end

  def set_current_ride
    @current_ride = current_user.rides.last
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    users_rides_path
  end

  def after_sign_up_path_for(resource)
    users_rides_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins/rides_helper.rb
module Admins::RidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/rides_helper.rb
module Users::RidesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/rides/index.html.erb
<% if @current_ride.present? && @current_ride.status != 'complete' %>

  <table class="table table-striped">
    <h3> Current Ride Request: </h3>

    <thead>
    <tr>
      <th>Rider</th>
      <th>Pick Up</th>
      <th>Passengers</th>
      <th>Accepted At</th>
      <th>Pickup</th>
      <th>Drop Off</th>
    </tr>
    </thead>

    <tbody>
    <tr>
      <% if @current_ride.user.present? %>
        <td><%= @current_ride.user.name.capitalize %></td>
      <% end %>
      <td><%= @current_ride.pick_up_location.capitalize %></td>
      <td><%= @current_ride.num_of_passengers %></td>
      <td><%= @current_ride.accepted_time %></td>
      <td>
        <% if @current_ride.accepted? %>
          <%= link_to "Customer Picked Up", picked_up_admins_ride_path(@current_ride) %>
        <% else %>
          <%= @current_ride.pickup_time %>
        <% end %>
      </td>

      <td>
        <% if @current_ride.in_transit? %>
          <%= link_to "Customer Dropped Off", dropped_off_admins_ride_path(@current_ride) %>
        <% end %>
      </td>
    </tr>
    </tbody>

  </table>
  <br>
  <hr>
  <br>
<% end %>

<table class="table table-striped">
  <h3> Available Rides: <%= @rides.where.not(status: 3).count %></h3>

  <thead>
  <tr>
    <th>Pick Up</th>
    <th>Number of Passengers</th>
    <th>Accept Ride?</th>
  </tr>
  </thead>

  <tbody>
    <% @rides.where.not(status: 3).each do |ride| %>
      <% if ride.num_of_passengers <= current_admin.car_passenger_capacity  %>
        <tr>
          <td><%= ride.pick_up_location.capitalize %></td>
          <td><%= ride.num_of_passengers %></td>
          <td>
            <% if current_admin.rides.all? { |each_ride| each_ride.complete? } %>
              <%= link_to "Accept", ride_accepted_admins_ride_path(ride) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>

<table class="table table-striped">
  <h3> Completed Rides: <%= @completed_rides.count %></h3>

  <thead>
  <tr>
    <th>Rider</th>
    <th>Driver</th>
    <th>Pick Up</th>
    <th>Drop Off</th>
    <th>Requested At</th>
    <th>Accepted At</th>
    <th>Pickup Time</th>
    <th>DropOff Time</th>
    <th>Cost</th>
  </tr>
  </thead>

  <tbody>
    <% @completed_rides.each do |ride| %>
    <tr>
      <td><%= ride.user.name.capitalize %></td>
      <td><%= ride.admin.name.capitalize %></td>
      <td><%= ride.pick_up_location.capitalize %></td>
      <td><%= ride.drop_off_location.capitalize %></td>
      <td><%= ride.created_at.strftime('%l:%M %P') %></td>
      <td><%= ride.accepted_time %></td>
      <td><%= ride.pickup_time %></td>
      <td><%= ride.dropoff_time %></td>
      <td>$<%= ride.cost.to_i %>.00</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goober</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="admin <%= [controller_name, action_name].join(' ') %>">

<div class="content">

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a href="/" class="navbar-brand">Goober</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav sign-out">
          <% if current_admin %>
            <li><%= link_to 'Dashboard', admins_rides_path %></li>

            <li><%= link_to 'Sign out', destroy_admin_session_path, :method => :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <br><br>
  <br><br>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-lg-12 rider-dashboard-header">
        <h1> <%= current_admin.name.capitalize %>'s Driver Dashboard </h1>
        <h5> Seat Capacity: <%= current_admin.car_passenger_capacity %></h5><br>
      </div>
    </div>
    <div id="page">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goober</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body class="user <%= [controller_name, action_name].join(' ') %>">
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Goober</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav sign-out">
        <% if current_user %>
          <li><%= link_to 'Dashboard', users_rides_path %></li>

          <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="content">

  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>

  <div id="page">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/users/rides/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 rider-dashboard-header">
      <h1> <%= current_user.name.capitalize %>'s Rider Dashboard </h1>
      <br>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12 request-ride-button" >
      <% if current_user.rides.all? { |ride| ride.complete? } %>
        <%= link_to "Request A Ride", new_users_ride_path, class: "btn btn-lg btn-default" %>
      <% end %>
    </div>
  </div>

  <table class="table table-striped">
    <h3> Current Ride Request: </h3>

    <thead>
    <tr>
      <th>Row</th>
      <th>Pick Up</th>
      <th>Drop Off</th>
      <th>Passengers</th>
      <th>Driver</th>
      <th>Requested At</th>
      <th>Accepted At</th>
      <th>Pickup Time</th>
    </tr>
    </thead>

    <% if @current_ride.present? && @current_ride.status != 'complete' %>

    <tbody>
    <tr>
      <td><%= @current_ride.pick_up_location.capitalize %></td>
      <td><%= @current_ride.drop_off_location.capitalize %></td>
      <td><%= @current_ride.num_of_passengers %></td>
      <% if @current_ride.admin.present? %>
        <td><%= @current_ride.admin.name.capitalize %></td>
      <% end %>
      <td><%= @current_ride.created_at.strftime('%l:%M %P') %></td>
      <td><%= @current_ride.accepted_time %></td>
      <td><%= @current_ride.accepted_time %></td>
      <td><%= @current_ride.pickup_time %></td>
    </tr>
    </tbody>

    <% end %>
  </table>

  <br>
  <hr>
  <br>


  <table class="table table-striped">
    <h3> Completed Rides: <%= @completed_rides.count %></h3>

    <thead>
    <tr>
      <th>Rider</th>
      <th>Driver</th>
      <th>Pick Up</th>
      <th>Drop Off</th>
      <th>Requested At</th>
      <th>Accepted At</th>
      <th>Pickup Time</th>
      <th>DropOff Time</th>
      <th>Cost</th>
    </tr>
    </thead>


    <tbody>
      <% @completed_rides.each do |ride| %>
        <tr>
          <td><%= ride.user.name.capitalize %></td>
          <td><%= ride.admin.name.capitalize %></td>
          <td><%= ride.pick_up_location.capitalize %></td>
          <td><%= ride.drop_off_location.capitalize %></td>
          <td><%= ride.created_at.strftime('%l:%M %P') %></td>
          <td><%= ride.accepted_time %></td>
          <td><%= ride.pickup_time %></td>
          <td><%= ride.dropoff_time %></td>
          <td>$<%= ride.cost.to_i %>.00</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/rides/new.html.erb
<div class="row">
  <div class="col-md-4"></div>

  <div class="col-md-4">
    <div class="form-new-user">
      <h2 class="form-new-user-heading">Enter Info below to reserve a ride </h2>

      <%= form_for @ride, url: users_rides_path do |f| %>
        <%#= devise_error_messages! %>

        <div class="field">
          <%= f.label :pick_up_location, "Pick Up Location" %>
          <%= f.text_field :pick_up_location, autofocus: true, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :drop_off_location, "Drop Off Location" %><br />
          <%= f.text_field :drop_off_location, autofocus: true, class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :num_of_passengers, "Number of Passengers" %>
          <%= f.number_field :num_of_passengers, autofocus: true, class: "form-control" %>
        </div><br>

        <div class="actions">
          <%= f.submit "Request Ride", class: "btn btn-default"%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid container-home">
  <div class="row"></div>

  <div class="row">
    <div class="col-md-12 welcome-block">
      <h1 class="home"> Welcome to Goober </h1>
      <h2 class="home"> It's like Uber for ... Uber </h2>
      <h3 class="home"> Sign Up or Sign In as:</h3>
      <ul class="nav-link">
        <%= link_to 'A Rider', new_user_session_path, :method => :get, class: "btn btn-lg btn-default btn-home" %>
        <%= link_to 'A Driver', new_admin_session_path, :method => :get, class: "btn btn-lg btn-default btn-home" %>
      </ul>
    </div>
  </div>

  <div class="row"></div>
</div>